# Generated by Django 3.2.4 on 2021-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='book_name',
            field=models.CharField(max_length=50, verbose_name='书名'),
        ),
    ]
