# Generated by Django 3.2.4 on 2021-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, unique=True, verbose_name='书名')),
                ('book_price', models.FloatField(verbose_name='价格')),
                ('book_author', models.CharField(max_length=20, verbose_name='作者')),
                ('book_sales', models.IntegerField(verbose_name='销量')),
                ('book_stock', models.IntegerField(verbose_name='库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
